#!/bin/bash
# put this in /usr/bin/ as per FHS
apt-get update 		&&
apt-get check 		&&
apt-get upgrade -f 	&&
apt-get dist-upgrade -f	&&
dpkg --configure -a     &&
apt-get autoclean 	&&
apt-get autoremove -f	&&
aptitude purge '~c'
