#!/bin/bash
# put this in /usr/local/bin/ as per FHS
DEV="wlan0"
DRVR="nl80211"
#DRVR="wext"
CONF='/etc/wpa_supplicant/wpa_supplicant.conf'
echo "[1]  bringing up device $DEV"			&&
ip link set $DEV up					&&
echo "[2]  loading wpa configuration"			&&
wpa_supplicant -B -D $DRVR -i $DEV -c $CONF		&&
echo "[3]  starting dhcpcd service"			&&
dhcpcd wlan0 -t 0					&&
echo "[   wireless network is up   ]"
